server = "https://mcr.microsoft.com"
 
[host."https://mcr.m.daocloud.io"]
  capabilities = ["pull", "resolve", "push"]

[host."https://mcr.mirrorify.net"]
  capabilities = ["pull", "resolve", "push"]
