server = "https://k8s.gcr.io"
 
[host."https://k8s-gcr.m.daocloud.io"]
  capabilities = ["pull", "resolve", "push"]

[host."https://k8s-gcr.mirrorify.net"]
  capabilities = ["pull", "resolve", "push"]
